# Building mySQL Data-base

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)


import numpy as np

import warnings
warnings.filterwarnings('ignore')


import pylab as plt  # import matplotlib.pyplot as plt
import seaborn as sns

# 1. Exploración inicial.

# 1.1 DataFrame Actor. (LIMPIA)

In [2]:
df_original_actor = pd.read_csv('data/actor.csv', encoding='latin1')
df_actor = df_original_actor.copy()

In [3]:
dim_original_actor = df_actor.shape # De esta forma guardo las dimensiones del data frame original.
df_actor.shape

(200, 4)

In [4]:
df_actor.head()

actor_id first_name     last_name          last_update
0         1   PENELOPE       GUINESS  2006-02-15 04:34:33
1         2       NICK      WAHLBERG  2006-02-15 04:34:33
2         3         ED         CHASE  2006-02-15 04:34:33
3         4   JENNIFER         DAVIS  2006-02-15 04:34:33
4         5     JOHNNY  LOLLOBRIGIDA  2006-02-15 04:34:33

In [5]:
df_actor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   actor_id     200 non-null    int64 
 1   first_name   200 non-null    object
 2   last_name    200 non-null    object
 3   last_update  200 non-null    object
dtypes: int64(1), object(3)
memory usage: 6.4+ KB


In [6]:
df_actor.actor_id.unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [7]:
df_actor.first_name.unique()

array(['PENELOPE', 'NICK', 'ED', 'JENNIFER', 'JOHNNY', 'BETTE', 'GRACE',
       'MATTHEW', 'JOE', 'CHRISTIAN', 'ZERO', 'KARL', 'UMA', 'VIVIEN',
       'CUBA', 'FRED', 'HELEN', 'DAN', 'BOB', 'LUCILLE', 'KIRSTEN',
       'ELVIS', 'SANDRA', 'CAMERON', 'KEVIN', 'RIP', 'JULIA', 'WOODY',
       'ALEC', 'SISSY', 'TIM', 'MILLA', 'AUDREY', 'JUDY', 'BURT', 'VAL',
       'TOM', 'GOLDIE', 'JODIE', 'KIRK', 'REESE', 'PARKER', 'FRANCES',
       'ANNE', 'NATALIE', 'GARY', 'CARMEN', 'MENA', 'FAY', 'JUDE',
       'DUSTIN', 'HENRY', 'JAYNE', 'RAY', 'ANGELA', 'MARY', 'JESSICA',
       'KENNETH', 'MICHELLE', 'ADAM', 'SEAN', 'ANGELINA', 'CARY',
       'GROUCHO', 'MAE', 'RALPH', 'SCARLETT', 'BEN', 'JAMES', 'MINNIE',
       'GREG', 'SPENCER', 'CHARLIZE', 'CHRISTOPHER', 'ELLEN', 'DARYL',
       'GENE', 'MEG', 'CHRIS', 'JIM', 'SUSAN', 'WALTER', 'SIDNEY', 'GINA',
       'WARREN', 'SYLVESTER', 'RUSSELL', 'MORGAN', 'HARRISON', 'RENEE',
       'LIZA', 'SALMA', 'JULIANNE', 'ALBERT', 'CATE', 'GRETA', 'JANE',
       '

In [8]:
df_actor.last_name.unique()

array(['GUINESS', 'WAHLBERG', 'CHASE', 'DAVIS', 'LOLLOBRIGIDA',
       'NICHOLSON', 'MOSTEL', 'JOHANSSON', 'SWANK', 'GABLE', 'CAGE',
       'BERRY', 'WOOD', 'BERGEN', 'OLIVIER', 'COSTNER', 'VOIGHT', 'TORN',
       'FAWCETT', 'TRACY', 'PALTROW', 'MARX', 'KILMER', 'STREEP', 'BLOOM',
       'CRAWFORD', 'MCQUEEN', 'HOFFMAN', 'WAYNE', 'PECK', 'SOBIESKI',
       'HACKMAN', 'DEAN', 'DUKAKIS', 'BOLGER', 'MCKELLEN', 'BRODY',
       'DEGENERES', 'MIRANDA', 'JOVOVICH', 'STALLONE', 'GOLDBERG',
       'BARRYMORE', 'DAY-LEWIS', 'CRONYN', 'HOPKINS', 'PHOENIX', 'HUNT',
       'TEMPLE', 'PINKETT', 'HARRIS', 'CRUISE', 'AKROYD', 'TAUTOU',
       'NEESON', 'WRAY', 'HUDSON', 'TANDY', 'BAILEY', 'WINSLET',
       'MCCONAUGHEY', 'GRANT', 'WILLIAMS', 'PENN', 'KEITEL', 'POSEY',
       'ASTAIRE', 'SINATRA', 'CRUZ', 'DAMON', 'JOLIE', 'WILLIS', 'PITT',
       'ZELLWEGER', 'CHAPLIN', 'PESCI', 'DENCH', 'PRESLEY', 'HAWKE',
       'BRIDGES', 'DEPP', 'LEIGH', 'CROWE', 'DUNST', 'NOLTE', 'DERN',
       'BACALL', 'MCDORMA

In [9]:
df_actor.last_update.unique()

array(['2006-02-15 04:34:33'], dtype=object)

In [10]:
#al ser una columna constante y que nonos aporta nada de información, también la voy a eliminar

In [11]:
df_actor.drop(columns=['last_update'], inplace=True)

In [12]:
df_actor.head()

actor_id first_name     last_name
0         1   PENELOPE       GUINESS
1         2       NICK      WAHLBERG
2         3         ED         CHASE
3         4   JENNIFER         DAVIS
4         5     JOHNNY  LOLLOBRIGIDA

In [13]:
df_actor['actor_name'] = df_actor['first_name'] + ' ' + df_actor['last_name']

In [14]:
#como he juntado dos columnas en una nueva voy a eliminar las dos que había y reordenarlo

In [15]:
df_actor.drop(columns=['first_name'], inplace=True)
df_actor.drop(columns=['last_name'], inplace=True)

In [16]:
nuevo_orden_actor = ["actor_id", "actor_name"]

In [17]:
df_actor.head()

actor_id           actor_name
0         1     PENELOPE GUINESS
1         2        NICK WAHLBERG
2         3             ED CHASE
3         4       JENNIFER DAVIS
4         5  JOHNNY LOLLOBRIGIDA

In [18]:
df_actor["actor_name"].value_counts().head()

SUSAN DAVIS       2
EWAN GOODING      1
DARYL CRAWFORD    1
GRETA KEITEL      1
JANE JACKMAN      1
Name: actor_name, dtype: int64

In [19]:
fila_susan = df_actor[df_actor['actor_name'] == 'SUSAN DAVIS']
fila_susan

actor_id   actor_name
100       101  SUSAN DAVIS
109       110  SUSAN DAVIS

In [20]:
df_actor = df_actor.drop(109)

In [21]:
df_actor = df_actor.reset_index(drop=True)

In [22]:
df_actor.head()

actor_id           actor_name
0         1     PENELOPE GUINESS
1         2        NICK WAHLBERG
2         3             ED CHASE
3         4       JENNIFER DAVIS
4         5  JOHNNY LOLLOBRIGIDA

In [23]:
df_actor.shape

(199, 2)

# 1.2 DataFrame Category.

In [24]:
df_original_category = pd.read_csv('data/category.csv', encoding='latin1')
df_category = df_original_category.copy()

In [25]:
dim_original_category = df_category.shape # De esta forma guardo las dimensiones del data frame original.
df_category.shape

(16, 3)

In [26]:
df_category.head()

category_id       name          last_update
0            1     Action  2006-02-15 04:46:27
1            2  Animation  2006-02-15 04:46:27
2            3   Children  2006-02-15 04:46:27
3            4   Classics  2006-02-15 04:46:27
4            5     Comedy  2006-02-15 04:46:27

In [27]:
df_category.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   category_id  16 non-null     int64 
 1   name         16 non-null     object
 2   last_update  16 non-null     object
dtypes: int64(1), object(2)
memory usage: 516.0+ bytes


In [28]:
df_category.category_id.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [29]:
df_category.name.unique()

array(['Action', 'Animation', 'Children', 'Classics', 'Comedy',
       'Documentary', 'Drama', 'Family', 'Foreign', 'Games', 'Horror',
       'Music', 'New', 'Sci-Fi', 'Sports', 'Travel'], dtype=object)

In [30]:
df_category.last_update.unique()

array(['2006-02-15 04:46:27'], dtype=object)

In [31]:
#al ser una columna constante y que nonos aporta nada de información, la voy a eliminar.

In [32]:
df_category.drop(columns=['last_update'], inplace=True)

In [33]:
df_category["name"].value_counts().head()

Action       1
Animation    1
Children     1
Classics     1
Comedy       1
Name: name, dtype: int64

In [34]:
#quiero cambiar el nombre de la columna name

In [35]:
df_category.rename(columns={'name': 'category_name'}, inplace=True)

In [36]:
df_category.head()

category_id category_name
0            1        Action
1            2     Animation
2            3      Children
3            4      Classics
4            5        Comedy

# 1.3 DataFrame Film.

In [37]:
df_original_film = pd.read_csv('data/film.csv', encoding='latin1')
df_film = df_original_film.copy()

In [38]:
dim_original_film = df_film.shape # De esta forma guardo las dimensiones del data frame original.
df_film.shape

(1000, 13)

In [39]:
df_film.head()

film_id             title  \
0        1  ACADEMY DINOSAUR   
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   
3        4  AFFAIR PREJUDICE   
4        5       AFRICAN EGG   

                                         description  release_year  \
0  A Epic Drama of a Feminist And a Mad Scientist...          2006   
1  A Astounding Epistle of a Database Administrat...          2006   
2  A Astounding Reflection of a Lumberjack And a ...          2006   
3  A Fanciful Documentary of a Frisbee And a Lumb...          2006   
4  A Fast-Paced Documentary of a Pastry Chef And ...          2006   

   language_id  original_language_id  rental_duration  rental_rate  length  \
0            1                   NaN                6         0.99      86   
1            1                   NaN                3         4.99      48   
2            1                   NaN                7         2.99      50   
3            1                   NaN                5         2.99     117   
4            1                   NaN                6         2.99     130   

   replacement_cost rating                  special_features  \
0             20.99     PG  Deleted Scenes,Behind the Scenes   
1             12.99      G           Trailers,Deleted Scenes   
2             18.99  NC-17           Trailers,Deleted Scenes   
3             26.99      G    Commentaries,Behind the Scenes   
4             22.99      G                    Deleted Scenes   

           last_update  
0  2006-02-15 05:03:42  
1  2006-02-15 05:03:42  
2  2006-02-15 05:03:42  
3  2006-02-15 05:03:42  
4  2006-02-15 05:03:42

In [40]:
df_film.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   film_id               1000 non-null   int64  
 1   title                 1000 non-null   object 
 2   description           1000 non-null   object 
 3   release_year          1000 non-null   int64  
 4   language_id           1000 non-null   int64  
 5   original_language_id  0 non-null      float64
 6   rental_duration       1000 non-null   int64  
 7   rental_rate           1000 non-null   float64
 8   length                1000 non-null   int64  
 9   replacement_cost      1000 non-null   float64
 10  rating                1000 non-null   object 
 11  special_features      1000 non-null   object 
 12  last_update           1000 non-null   object 
dtypes: float64(3), int64(5), object(5)
memory usage: 101.7+ KB


In [41]:
#Primero voy a eliminar la columna de original language porque son todos los valores nulos.

In [42]:
df_film.drop(columns=['original_language_id'], inplace=True)

In [43]:
cte_cols_film = []
for c in df_film.select_dtypes(include=np.number):   # para cada columna numerica.....
    if len(df_film[c].unique()) == 1:
        cte_cols_film.append(c)
cte_cols_film   

['release_year', 'language_id']

In [44]:
#En primer lugar, voy a eliminar las columnas de 'release_year' y 'language_id' al ser columnas constantes y que no nos aportan nada de información.

In [45]:
df_film.drop(columns=['release_year'], inplace=True)

In [46]:
df_film.drop(columns=['language_id'], inplace=True)

In [47]:
#ahora voy a comprobar la columna last update porque con la función de arriba he identificado las ctes numéricas pero esta columna no lo es

In [48]:
df_film.last_update.unique()

array(['2006-02-15 05:03:42'], dtype=object)

In [49]:
#parece ser que también lo es

In [50]:
df_film.drop(columns=['last_update'], inplace=True)

In [51]:
#df_film.film_id.unique()

In [52]:
#df_film.title.unique()

In [53]:
#df_film.description.unique()

In [54]:
df_film.rental_duration.unique()

array([6, 3, 7, 5, 4])

In [55]:
#df_film.rental_rate.unique()

In [56]:
#df_film.length.unique()

In [57]:
#df_film.special_features.unique()

In [58]:
#df_film.length.unique()

In [59]:
#Vamos a mirar las columnas con baja varianza

In [60]:
df_film.describe().T

count     mean         std    min     25%     50%     75%  \
film_id           1000.0  500.500  288.819436   1.00  250.75  500.50  750.25   
rental_duration   1000.0    4.985    1.411654   3.00    4.00    5.00    6.00   
rental_rate       1000.0    2.980    1.646393   0.99    0.99    2.99    4.99   
length            1000.0  115.272   40.426332  46.00   80.00  114.00  149.25   
replacement_cost  1000.0   19.984    6.050833   9.99   14.99   19.99   24.99   

                      max  
film_id           1000.00  
rental_duration      7.00  
rental_rate          4.99  
length             185.00  
replacement_cost    29.99

In [61]:
#observamos que no hay ningún valor especialemnte atípico.

In [62]:
df_film.head()

film_id             title  \
0        1  ACADEMY DINOSAUR   
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   
3        4  AFFAIR PREJUDICE   
4        5       AFRICAN EGG   

                                         description  rental_duration  \
0  A Epic Drama of a Feminist And a Mad Scientist...                6   
1  A Astounding Epistle of a Database Administrat...                3   
2  A Astounding Reflection of a Lumberjack And a ...                7   
3  A Fanciful Documentary of a Frisbee And a Lumb...                5   
4  A Fast-Paced Documentary of a Pastry Chef And ...                6   

   rental_rate  length  replacement_cost rating  \
0         0.99      86             20.99     PG   
1         4.99      48             12.99      G   
2         2.99      50             18.99  NC-17   
3         2.99     117             26.99      G   
4         2.99     130             22.99      G   

                   special_features  
0  Deleted Scenes,Behind the Scenes  
1           Trailers,Deleted Scenes  
2           Trailers,Deleted Scenes  
3    Commentaries,Behind the Scenes  
4                    Deleted Scenes

In [63]:
df_film['special_features'] = df_film['special_features'].str.replace(',', ', ') #tras ver el dataframe he visto que falta un hueco detras de la "," en la última columna.

In [64]:
df_film.head()

film_id             title  \
0        1  ACADEMY DINOSAUR   
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   
3        4  AFFAIR PREJUDICE   
4        5       AFRICAN EGG   

                                         description  rental_duration  \
0  A Epic Drama of a Feminist And a Mad Scientist...                6   
1  A Astounding Epistle of a Database Administrat...                3   
2  A Astounding Reflection of a Lumberjack And a ...                7   
3  A Fanciful Documentary of a Frisbee And a Lumb...                5   
4  A Fast-Paced Documentary of a Pastry Chef And ...                6   

   rental_rate  length  replacement_cost rating  \
0         0.99      86             20.99     PG   
1         4.99      48             12.99      G   
2         2.99      50             18.99  NC-17   
3         2.99     117             26.99      G   
4         2.99     130             22.99      G   

                    special_features  
0  Deleted Scenes, Behind the Scenes  
1           Trailers, Deleted Scenes  
2           Trailers, Deleted Scenes  
3    Commentaries, Behind the Scenes  
4                     Deleted Scenes

# 1.4 DataFrame Inventory.

In [65]:
df_original_inventory = pd.read_csv('data/inventory.csv', encoding='latin1')
df_inventory = df_original_inventory.copy()

In [66]:
dim_original_inventory = df_inventory.shape # De esta forma guardo las dimensiones del data frame original.
df_inventory.shape

(1000, 4)

In [67]:
df_inventory.head()

inventory_id  film_id  store_id          last_update
0             1        1         1  2006-02-15 05:09:17
1             2        1         1  2006-02-15 05:09:17
2             3        1         1  2006-02-15 05:09:17
3             4        1         1  2006-02-15 05:09:17
4             5        1         2  2006-02-15 05:09:17

In [68]:
df_inventory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   inventory_id  1000 non-null   int64 
 1   film_id       1000 non-null   int64 
 2   store_id      1000 non-null   int64 
 3   last_update   1000 non-null   object
dtypes: int64(3), object(1)
memory usage: 31.4+ KB


In [69]:
cte_cols_inventory = []
for c in df_inventory.select_dtypes(include=np.number):   # para cada columna numerica.....
    if len(df_inventory[c].unique()) == 1:
        cte_cols.append(c)
cte_cols_inventory   

[]

In [70]:
#no hay ninguna columna numérica cte.

In [71]:
df_inventory.last_update.unique()

array(['2006-02-15 05:09:17'], dtype=object)

In [72]:
df_inventory.drop(columns=['last_update'], inplace=True)

In [73]:
df_inventory.store_id.unique()

array([1, 2])

In [74]:
#observamos que debía haber dos tindas, no se relaciona con ninguna otra tabla perp puede ser interesante para ver qué localización era mejor

In [75]:
df_inventory.head()

inventory_id  film_id  store_id
0             1        1         1
1             2        1         1
2             3        1         1
3             4        1         1
4             5        1         2

In [76]:
#df_inventory.inventory_id.unique() #aquí  hay 1000 y en el de rental hay muchos más

# 1.4 DataFrame Language. (LIMPIA)

In [77]:
df_original_language = pd.read_csv('data/language.csv', encoding='latin1')
df_language = df_original_language.copy()

In [78]:
dim_original_language = df_language.shape # De esta forma guardo las dimensiones del data frame original.
df_language.shape

(6, 3)

In [79]:
df_language.head(7)

language_id      name          last_update
0            1   English  2006-02-15 05:02:19
1            2   Italian  2006-02-15 05:02:19
2            3  Japanese  2006-02-15 05:02:19
3            4  Mandarin  2006-02-15 05:02:19
4            5    French  2006-02-15 05:02:19
5            6    German  2006-02-15 05:02:19

In [80]:
df_language.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   language_id  6 non-null      int64 
 1   name         6 non-null      object
 2   last_update  6 non-null      object
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes


In [81]:
#otra vez más, nos deshacemos de la columna last-update

In [82]:
df_language.last_update.unique()

array(['2006-02-15 05:02:19'], dtype=object)

In [83]:
df_language.drop(columns=['last_update'], inplace=True)

In [84]:
df_language.language_id.unique()

array([1, 2, 3, 4, 5, 6])

In [85]:
df_language.name.unique()

array(['English', 'Italian', 'Japanese', 'Mandarin', 'French', 'German'],
      dtype=object)

In [86]:
df_language.head()

language_id      name
0            1   English
1            2   Italian
2            3  Japanese
3            4  Mandarin
4            5    French

# 1.5 DataFrame old_HDD. (lo del actor_id y el film_id no está bien tal y como está )

In [87]:
df_original_old_hdd = pd.read_csv('data/old_HDD.csv', encoding='latin1')
df_old_hdd = df_original_old_hdd.copy()

In [88]:
dim_original_old_hdd = df_old_hdd.shape # De esta forma guardo las dimensiones del data frame original.
df_old_hdd.shape

(1000, 5)

In [89]:
df_old_hdd.head()

first_name last_name                  title  release_year  category_id
0   PENELOPE   GUINESS       ACADEMY DINOSAUR          2006            6
1   PENELOPE   GUINESS   ANACONDA CONFESSIONS          2006            2
2   PENELOPE   GUINESS            ANGELS LIFE          2006           13
3   PENELOPE   GUINESS  BULWORTH COMMANDMENTS          2006           10
4   PENELOPE   GUINESS          CHEAPER CLYDE          2006           14

In [90]:
df_old_hdd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   first_name    1000 non-null   object
 1   last_name     1000 non-null   object
 2   title         1000 non-null   object
 3   release_year  1000 non-null   int64 
 4   category_id   1000 non-null   int64 
dtypes: int64(2), object(3)
memory usage: 39.2+ KB


In [91]:
cte_cols_old_hdd = []
for c in df_old_hdd.select_dtypes(include=np.number):   # para cada columna numerica.....   
    if len(df_old_hdd[c].unique()) == 1:    
        cte_cols_old_hdd.append(c)
cte_cols_old_hdd   

['release_year']

In [92]:
df_old_hdd.drop(columns=['release_year'], inplace=True)

In [93]:
df_old_hdd['actor_name'] = df_old_hdd['first_name'] + ' ' + df_old_hdd['last_name']

In [94]:
df_old_hdd.head()

first_name last_name                  title  category_id        actor_name
0   PENELOPE   GUINESS       ACADEMY DINOSAUR            6  PENELOPE GUINESS
1   PENELOPE   GUINESS   ANACONDA CONFESSIONS            2  PENELOPE GUINESS
2   PENELOPE   GUINESS            ANGELS LIFE           13  PENELOPE GUINESS
3   PENELOPE   GUINESS  BULWORTH COMMANDMENTS           10  PENELOPE GUINESS
4   PENELOPE   GUINESS          CHEAPER CLYDE           14  PENELOPE GUINESS

In [95]:
#y como he unido dos columnas en una, eliminaré las de name y apellidos

In [96]:
df_old_hdd.drop(columns=['first_name'], inplace=True)

In [97]:
df_old_hdd.drop(columns=['last_name'], inplace=True)

In [98]:
df_old_hdd.head()

title  category_id        actor_name
0       ACADEMY DINOSAUR            6  PENELOPE GUINESS
1   ANACONDA CONFESSIONS            2  PENELOPE GUINESS
2            ANGELS LIFE           13  PENELOPE GUINESS
3  BULWORTH COMMANDMENTS           10  PENELOPE GUINESS
4          CHEAPER CLYDE           14  PENELOPE GUINESS

In [99]:
#He añadido actor_id y fil_id

In [100]:
df_old_hdd = df_old_hdd.merge(df_actor[['actor_name', 'actor_id']], on='actor_name', how='left')

In [101]:
df_old_hdd = df_old_hdd.merge(df_film[['title', 'film_id']], on='title', how='left')

In [102]:
df_old_hdd.head()

title  category_id        actor_name  actor_id  film_id
0       ACADEMY DINOSAUR            6  PENELOPE GUINESS         1        1
1   ANACONDA CONFESSIONS            2  PENELOPE GUINESS         1       23
2            ANGELS LIFE           13  PENELOPE GUINESS         1       25
3  BULWORTH COMMANDMENTS           10  PENELOPE GUINESS         1      106
4          CHEAPER CLYDE           14  PENELOPE GUINESS         1      140

#En el caso concreto que proporcionaste, donde tienes una tabla que contiene películas y otra tabla que contiene categorías, es razonable mantener la relación entre ambas tablas utilizando una clave externa (category_id) en la tabla de películas. Esto sigue el principio de normalización de bases de datos y presenta varios beneficios:

Integridad de los datos: Al mantener una relación, puedes garantizar que las películas se asignen correctamente a las categorías mediante la clave externa (category_id). Esto previene la entrada de datos incorrectos o inconsistentes.
Eficiencia en el almacenamiento: Evitas la duplicación de datos innecesaria, lo que ahorra espacio de almacenamiento, especialmente si tienes muchas películas en diferentes categorías.
Facilita la actualización de categorías: Si necesitas modificar o agregar categorías en el futuro, solo tendrás que hacerlo en la tabla de categorías. Las películas relacionadas seguirán vinculadas a sus categorías correspondientes sin necesidad de cambios en la tabla de películas.
Facilita las consultas complejas: Si en el futuro necesitas realizar consultas que involucren la relación entre películas y categorías, mantener la relación facilitará estas consultas.
Por lo tanto, en este caso, te recomendaría mantener la relación y normalizar los datos, es decir, mantener las categorías en una tabla independiente y utilizar una clave externa para relacionar las películas con sus categorías. Esto ayudará a mantener la integridad de los datos y permitirá un mejor manejo de la información

In [103]:
#ahora quiero cambiar el orden de las columnas

In [104]:
nuevo_orden = ['actor_id', 'film_id', 'name', 'title', 'category_id']

In [105]:
df_old_hdd = df_old_hdd.reindex(columns=nuevo_orden)

In [106]:
df_old_hdd.head()

actor_id  film_id  name                  title  category_id
0         1        1   NaN       ACADEMY DINOSAUR            6
1         1       23   NaN   ANACONDA CONFESSIONS            2
2         1       25   NaN            ANGELS LIFE           13
3         1      106   NaN  BULWORTH COMMANDMENTS           10
4         1      140   NaN          CHEAPER CLYDE           14

# 1.6 DataFrame rental. (LIMPIARLA)

In [107]:
df_original_rental = pd.read_csv('data/rental.csv', encoding='latin1')
df_rental = df_original_rental.copy()

In [108]:
dim_original_rental = df_rental.shape # De esta forma guardo las dimensiones del data frame original.
df_rental.shape

(1000, 7)

In [109]:
df_rental.head() 

rental_id          rental_date  inventory_id  customer_id  \
0          1  2005-05-24 22:53:30           367          130   
1          2  2005-05-24 22:54:33          1525          459   
2          3  2005-05-24 23:03:39          1711          408   
3          4  2005-05-24 23:04:41          2452          333   
4          5  2005-05-24 23:05:21          2079          222   

           return_date  staff_id          last_update  
0  2005-05-26 22:04:30         1  2006-02-15 21:30:53  
1  2005-05-28 19:40:33         1  2006-02-15 21:30:53  
2  2005-06-01 22:12:39         1  2006-02-15 21:30:53  
3  2005-06-03 01:43:41         2  2006-02-15 21:30:53  
4  2005-06-02 04:33:21         1  2006-02-15 21:30:53

In [110]:
df_rental.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   rental_id     1000 non-null   int64 
 1   rental_date   1000 non-null   object
 2   inventory_id  1000 non-null   int64 
 3   customer_id   1000 non-null   int64 
 4   return_date   1000 non-null   object
 5   staff_id      1000 non-null   int64 
 6   last_update   1000 non-null   object
dtypes: int64(4), object(3)
memory usage: 54.8+ KB


In [111]:
df_rental.last_update.unique()

array(['2006-02-15 21:30:53'], dtype=object)

In [112]:
df_rental.drop(columns=['last_update'], inplace=True)

In [113]:
df_rental['rental_date'] = pd.to_datetime(df_rental['rental_date'])

In [114]:
df_rental['rental_date'] = df_rental['rental_date'].dt.date

In [115]:
#y el tiempo concretoi nos da igual porque en el apartado de film solo tenemos cuanto tiempo (en días9 la gente ) ha alquiulado la película, por lo que la hora concreta nos da igual. 

In [116]:
df_rental.head()

rental_id rental_date  inventory_id  customer_id          return_date  \
0          1  2005-05-24           367          130  2005-05-26 22:04:30   
1          2  2005-05-24          1525          459  2005-05-28 19:40:33   
2          3  2005-05-24          1711          408  2005-06-01 22:12:39   
3          4  2005-05-24          2452          333  2005-06-03 01:43:41   
4          5  2005-05-24          2079          222  2005-06-02 04:33:21   

   staff_id  
0         1  
1         1  
2         1  
3         2  
4         1

In [117]:
df_rental['return_date'] = pd.to_datetime(df_rental['return_date'])

In [118]:
df_rental['return_date'] = df_rental['return_date'].dt.date

In [119]:
df_rental.rental_date.unique()

array([datetime.date(2005, 5, 24), datetime.date(2005, 5, 25),
       datetime.date(2005, 5, 26), datetime.date(2005, 5, 27),
       datetime.date(2005, 5, 28), datetime.date(2005, 5, 29),
       datetime.date(2005, 5, 30), datetime.date(2005, 5, 31)],
      dtype=object)

In [120]:
df_rental.head() 

rental_id rental_date  inventory_id  customer_id return_date  staff_id
0          1  2005-05-24           367          130  2005-05-26         1
1          2  2005-05-24          1525          459  2005-05-28         1
2          3  2005-05-24          1711          408  2005-06-01         1
3          4  2005-05-24          2452          333  2005-06-03         2
4          5  2005-05-24          2079          222  2005-06-02         1

In [121]:
df_rental.inventory_id.unique()

array([ 367, 1525, 1711, 2452, 2079, 2792, 3995, 2346, 2580, 1824, 4443,
       1584, 2294, 2701, 3049,  389,  830, 3376, 1941, 3517,  146,  727,
       4441, 3273, 3961, 4371, 1225, 4068,  611, 3744, 4482, 3832, 1681,
       2613, 1286, 1308,  403, 2540, 4466, 2638, 1761,  380, 2578, 3098,
       1853, 3318, 2211, 1780, 2965, 1983, 1257, 4017, 1255, 2787, 1139,
       1352, 3938, 3050, 2884,  330, 4210,  261, 4008,   79, 3552, 1162,
        239, 4029, 3207, 2168, 2408, 2260,  517, 1744, 3393, 3021, 1303,
       4067, 3299, 2478, 2610, 1388,  466, 1829,  470, 2275, 1586, 2221,
       2181, 2984,  139,  775, 4360, 1675,  178, 3418, 1283, 2970,  535,
       2599,  617,  373, 3343, 4281,  794, 3627, 2833, 3289, 1044, 4108,
       3725, 2153, 2963, 4502,  749, 4453, 4278,  872, 1359,   37, 1053,
       2908, 1795,  212,  952, 2047, 2026, 4322, 4154, 3990,  815, 3367,
        399, 2272,  103, 2296, 2591, 4134,  327,  655,  811, 4407,  847,
       1689, 3905, 1431,  633, 4252, 1084,  909, 29

In [122]:
#aquí hay muchos más regisros que en la parte de inventory_id en inventory, por lo que todos los números que sena más allá del 1000 los eliminaré.

In [123]:
df_rental = df_rental[df_rental.inventory_id < 1001]

In [124]:
df_rental.inventory_id.unique()

array([367, 389, 830, 146, 727, 611, 403, 380, 330, 261,  79, 239, 517,
       466, 470, 139, 775, 178, 535, 617, 373, 794, 749, 872,  37, 212,
       952, 815, 399, 103, 327, 655, 811, 847, 633, 909, 288, 887, 865,
       851, 984, 506, 190, 776, 674, 303, 102, 729, 764, 679, 651, 214,
       511, 715, 241, 503, 131, 368,  30, 435, 207, 971, 656, 182, 661,
       350, 314, 485, 249, 187, 593,  26, 751, 946, 141,   6, 833, 360,
       944, 955, 910, 434, 691, 263, 145, 752, 553, 258, 461, 619, 129,
       354, 723, 205, 597, 826,  20, 339, 802, 424,  72, 393, 184, 458,
       601,  71, 667, 225, 234, 266, 992, 530, 487,  23, 158, 644, 928,
        53, 375, 898,  95, 473, 377, 638, 595, 821, 599, 270, 280, 989,
       452, 425,  58, 495, 140, 739, 126, 331, 848,  87, 797, 227, 697,
       907, 742, 800, 635, 592, 130, 500, 372, 819, 194,  85, 267, 933,
       242, 769, 600, 273, 581, 730, 734, 515, 687, 353, 245, 451, 533,
        88,  39, 763, 708, 379, 609, 441, 785, 630, 186, 623, 71

In [ ]:
#Quiero restar el return date - el rental date para saber cuantos días se tienen las pelis en casa

In [129]:

# diferencia entre las fechas
df_rental['rental_duration'] = (df_rental['return_date'] - df_rental['rental_date']).dt.days


In [130]:
df_rental.rental_duration.unique() #3,4,5,6,7

array([ 2,  1,  5,  4,  6,  9,  7,  8,  3,  0, 10])

In [131]:
df_rental.rental_date.unique()

array([datetime.date(2005, 5, 24), datetime.date(2005, 5, 25),
       datetime.date(2005, 5, 26), datetime.date(2005, 5, 27),
       datetime.date(2005, 5, 28), datetime.date(2005, 5, 29),
       datetime.date(2005, 5, 30), datetime.date(2005, 5, 31)],
      dtype=object)

In [132]:
df_rental.return_date.unique()

array([datetime.date(2005, 5, 26), datetime.date(2005, 5, 27),
       datetime.date(2005, 5, 30), datetime.date(2005, 5, 29),
       datetime.date(2005, 5, 31), datetime.date(2005, 6, 3),
       datetime.date(2005, 6, 1), datetime.date(2005, 6, 2),
       datetime.date(2005, 5, 28), datetime.date(2005, 6, 4),
       datetime.date(2005, 6, 5), datetime.date(2005, 6, 6),
       datetime.date(2005, 6, 7), datetime.date(2005, 6, 8)], dtype=object)

In [133]:
#podemos ver que los datos aquí no son muy consistentes. Realmente no nos aportan gran informaación para el estudio `porque no podemos generalizarla.
#en primer lugar, los datos están recogidos solo en un periodo muy corto de tiempo (solo el mes de mayo y junio) por lo que es una infotmación con la que no se puede hacer un estudio claro. Muestra muy pequeña.
#en segundo lugar, el periordo en el que la gente se queda las peliculas es diferente con respecto al de films. Donde los periorod soo oscilan entre 2 y 7. por lo tanto, solo conservaremos esos datos, el resto de datos, lo que no contienenuno de estos números, los eliminaremos. No podemos fiarnos, al igua que con los número que tienen un inventory_id mayor de 1000. 

In [134]:
#puede obeservarse que hay algo que tiene que estar mal porque la rental duration no coincide con la rental duration de la tabla fil. 

In [135]:
rental_durations_coincidentes = [3, 4, 5, 6, 7]
df_rental = df_rental[df_rental['rental_duration'].isin(rental_durations_coincidentes)]

In [136]:
df_rental.rental_duration.unique()

array([5, 4, 6, 7, 3])